name: CD Pipeline

on:
workflow_dispatch:

jobs:
deploy:
runs-on: ubuntu-latest

steps:
  - name: Checkout Code
    uses: actions/checkout@v3

  - name: Configure AWS (OIDC)
    uses: aws-actions/configure-aws-credentials@v2
    with:
      role-to-assume: YOUR_IAM_ROLE_ARN
      aws-region: ap-south-1

  - name: Install Dependencies
    run: npm install

  - name: Build Project
    run: npm run build

  - name: Deploy DEV
    if: github.ref == 'refs/heads/dev'
    run: |
      aws s3 sync dist/ s3://YOUR_DEV_BUCKET --delete
      aws cloudfront create-invalidation \
        --distribution-id DEV_DIST_ID \
        --paths "/*"

  - name: Deploy PROD
    if: github.ref == 'refs/heads/prod'
    run: |
      aws s3 sync dist/ s3://YOUR_PROD_BUCKET --delete
      aws cloudfront create-invalidation \
        --distribution-id PROD_DIST_ID \
        --paths "/*"

